### ISSUE TITLE
Way to remove basemaps so only my layer is visible?

### ISSUE THREAD

**Issue by markmnl** [microsoft/satellite-imagery-labeling-tool#15]
When using the labeler tool, I am using a WMS service added as a layer but sometimes the layer doesn't load for whatever reason.. 

Problem is Azure Maps Satellite base layer always does load so I'm worried labelers will label the wrong imagery..

Is there a way to make a project only load imagery from the WMS service ?

**Comment by rbrundritt** [comment]
Currently, if you don't specify Azure Maps credentials (or specify invalid credentials), the satellite imagery won't be loaded as a layer option and won't appear in the map. In the map_settings.js file you can set the auth info as follows to make it invalid:

```js
azureMapsAuth: {
	authType: "subscriptionKey",
	subscriptionKey: "<Your Azure Maps Key>"
}
```

If you are using the github.io hosted version, the map auth information is automatically set, so you won't be able to override this currently.
