### ISSUE TITLE
Drawn shapes not visibile when using GeoTIFF

### ISSUE THREAD

**Issue by markmnl** [microsoft/satellite-imagery-labeling-tool#16]
I can see the Number of shapes counter increasing but the shapes are not visible while drawing or after drawing.

Steps to reproduce:

- Add GeoTIFF layer as described here: https://github.com/microsoft/satellite-imagery-labeling-tool/blob/main/docs/GeoTiffs.md
- Using the labeler tool attemps to draw a shape
- Observe count increases but shapes are not visible

Maybe something to do wtih z index ?

**Comment by rbrundritt** [comment]
The Azure Maps team made a major change to how they style their vector tiles and broke a core feature of the SDK. Sadly they don't appear to plan on fixing this. I checked in a workaround last week, but see that there are several other related issues that I'm looking into now.

**Comment by rbrundritt** [comment]
I just checked in another fix. See if that resolves your issue.

**Comment by rbrundritt** [comment]
You might have to press CTRL+F5 to get the latest script files to load in the browser.

**Comment by markmnl** [comment]
updated and getting:

```
atlas.min.js:55  Error: _baseTranistLayer is not defined
    at atlas.min.js:55:17497
```

now, you can see here: https://ufooptix.org/label/labeler.html, I'm taking a look..

**Comment by rbrundritt** [comment]
I just pushed a fix. I was a bit too quick with the first fix.
