### ISSUE TITLE
Cant upload a local image as a layer

### ISSUE THREAD

**Issue by TarekDeek** [microsoft/satellite-imagery-labeling-tool#18]
Can't upload a local image as a layer using both the bounds and rotation and/or the corners. 

Instead the image appears as the entire map.

**Comment by TarekDeek** [comment]
I'm trying to overlay an aerial image above my property to increase quality of the labeling.

**Comment by TarekDeek** [comment]
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/669963d7-45bb-4b5a-80e4-563b10acbd00)

**Comment by rbrundritt** [comment]
I'm not able to reproduce this. Ensure that when passing in bounding box information the coordinates are in the format of "west,south,east,west". Also ensure the decimal place of the numbers is a period and not a comma (some language settings use commas) as this will likely result and very large numbers that cover the whole globe.

**Comment by TarekDeek** [comment]
> I'm not able to reproduce this. Ensure that when passing in bounding box information the coordinates are in the format of "west,south,east,west". Also ensure the decimal place of the numbers is a period and not a comma (some language settings use commas) as this will likely result and very large numbers that cover the whole globe.

For the load local image as a layer using corners. I input something like this 
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/06492339-ac4f-42b4-87f5-2a2dc74eb989)

Which still breaks the map 
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/f481dfb4-676a-4a4b-b9e4-b4ddb582c976)


Based on the format you provided they should be in Based on the coordinates provided, the format you're asking for is "west, south, east, north." Using this format I get. 

West: -73.486264
South: 45.460890
East: -73.484160
North: 45.461978

Therefore, the combined format is: 
-73.486264, 45.460890, -73.484160, 45.461978

So using that we can get. 
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/f4afd0d5-d0d2-4abf-a023-19e5b059d6cb)

Which doesn't work 
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/5f04f090-2ca8-45bd-a645-6e7dbcf85981)

**Comment by rbrundritt** [comment]
It looks like when using corners you have latitude/longitude reversed. In GIS the common standard is "longitude, latitude" as longitude is often associated with X in the terms of (x,y). 

I tried the bounding box coordinates you provided and they correctly showed that layer on the map. Note that the Azure Maps Aerial imagery always renders behind other layers. The primary reason for this is that includes vector labels that power the accessibility (screen reader describes the map as it moves). Note that your bounding box is really small (size of a residential property), so you need to zoom in more to see it. In my test, I was barely able to see the image at this bounding box when zoomed out as much as your last image.

**Comment by TarekDeek** [comment]
Apologies I forgot to mention my mistake earlier. I appreciate the time you have taken to debug my issue. I would like to share my entire workflow to portray my problem and frustration in making an image show up as a layer over the satellite imagery. 

0) First off the location of the image. 
LON, LAT : -73.48521244444444, 45.46143425
LAT, LON: 45.46143425, -73.48521244444444

![screenshot](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/ac9edc68-9863-4f3b-b069-36bfb95d908e)

1) Default Annotation Task Initial View
![Default Annotation Task Initial ](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/9b26fa9e-d351-4312-bf6a-2d9643ee5504)

Bounds : −73.488767, 45.460392, −73.481074, 45.462793
Corners: 
Top left:  -73.488684, 45.462793
Top Right: -73.481309, 45.462748
Bottom Left: -73.488767, 45.460807
Bottom Right: -73.481074, 45.460392

The image is saved locally on my machine, with a filename and type of : screenshot.png. Original image was of type JPEG but I saved a screenshot of it to see if PNG would work for me. 

2) Attempt to upload image using corners 

![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/373c0cce-ea13-4319-b16a-ed552aeee846)

3) Result, the entire map is my image lol. 

![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/9f7434c1-d9ed-4d60-b077-a05fe0029448)

4) Attempt to upload image using bounds and rotation. 
![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/04d7497c-5f2c-4794-a603-97b4bac15789)


5) Result , nothing shows up

![image](https://github.com/microsoft/satellite-imagery-labeling-tool/assets/77941062/12527636-52a0-4678-823a-91f2fb701c7f)


Again I thank you again and I hope you may help me in my task and find my mistake. 

Do I need to host the image on a server before being able to upload it ?
Do I need to use different filenames and/or image types ?

Can I see how it looks like when you attempt to recreate my behavior ?

**Comment by rbrundritt** [comment]
Well, this was a frustrating one to debug as it worked fine for me yesterday but had the issue today when I used the information you provided in your last post. The culprit... is that you are using a dash instead of hyphen as a negative sign, and the browsers `parseFloat` doesn't recognize it as a negative sign, and thus returned `NaN`, and this tool is failing over to a global bounding box as a result. I'll add some code to handle this odd scenario.

**Comment by TarekDeek** [comment]
OMG thank you so much when using bounds and rotation it works now but for corners it still seems to be finicky for me even after using the correct (-) keyboard input.

**Comment by rbrundritt** [comment]
Ok, think I got it this time. I overlooked a past pull request and missed a mistake that was checked in. Crazy enough the code still worked in some cases, but not in other. Should be corrected now.

**Comment by TarekDeek** [comment]
Can confirm it is working now, thanks !
