### ISSUE TITLE
Adjust brightness and contrast of image only

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/satellite-imagery-labeling-tool#2]
Hi, great work on this! I need to adjust the brightness and contrast (B&C) of my COG, but using the existing sliders also changes the B&C of the map. Not sure if this is (a) intended (b) a WIP or (c) a bug? 
Cheers

**Comment by rbrundritt** [comment]
Try version 2 of this project. The slides now adjust just the imagery. Note that v2 is a major upgrade and the data files from v1 are not compatible.

**Comment by rbrundritt** [comment]
If you want to quickly try this out, version 2 is hosted as a github.io page here: https://microsoft.github.io/satellite-imagery-labeling-tool/src/labeler.html On the left side panel click the layer button (second from the top), and you will see the image layer filters.

**Comment by robmarkcole** [comment]
Can confirm that resolves this issue, thanks @rbrundritt
