### ISSUE TITLE
Max zoom level of "Azure Maps Satellite" layer

### ISSUE THREAD

**Issue by patel-zeel** [microsoft/satellite-imagery-labeling-tool#26]
Hi, 

We are working on a research project and trying to use the labeling tool to generate the labels. For the completeness of the labeling process, we would like to know the maximum zoom level of the "Azure Maps Satellite" layer we can see through the labeling tool. We would like to include this detail in the manuscript to increase the confidence of the reviewers + readers in the quality of the labels. 

Could you please help with this?

**Comment by rbrundritt** [comment]
Azure Maps imagery is available to zoom level 19. It does get scaled after that when zooming into levels 19+. That said, the resolution of the imagery may vary be location, with remote areas having lower resolution imagery than urban.

**Comment by calebrob6** [comment]
Will also add you can see the min/max for the other preset layers here -- https://github.com/microsoft/satellite-imagery-labeling-tool/blob/main/src/settings/project_admin_settings.js#L31

**Comment by patel-zeel** [comment]
Thank you for taking the time to provide the insights, @rbrundritt and @calebrob6! Closing the issue as your answer addressed my question.
