### ISSUE TITLE
Local execution and modification

### ISSUE THREAD

**Issue by patel-zeel** [microsoft/satellite-imagery-labeling-tool#27]
Hi,

Is it possible to download and run this project locally? My primary motivation behind this is to be able to add/modify some features of the project based on our application. 

I tried cloning this repo and opening the `src/labeler.html` file locally, but it didn't work.
![image](https://github.com/user-attachments/assets/c11863db-2ca3-404a-9c49-52b7b0bb0921)

Edit:

I just saw [this help](https://github.com/microsoft/satellite-imagery-labeling-tool?tab=readme-ov-file#list-of-third-party-javascript-librariesversions). I am trying it but meanwhile I'd appreciate any help from the developers such as steps to follow to get it working locally. I am trying to do this on Macbook Pro M1 (2020) if that helps.

**Comment by rbrundritt** [comment]
Yes, it can be run locally, but it needs to be hosted on localhost, not just the filesystem (browsers generally limit access to the local filesystem). This is why the web page is unable to load the labeler.js file. 

An easy option is to use VSCode (that is what was used to build this project) or Visual studio.

In VSCode, I use an extension that deploys to localhost automatically called "Live Server". https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
Once that is installed, simple right click on the webpage and click on "Open with Live Server".

If you are using the full-blown Visual Studio, you can simply right click on the webpage and select "view in browser" and it will automatically deploy it to localhost.

**Comment by patel-zeel** [comment]
> https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

This extension worked smoothly. Thank you for a quick and fully working solution, @rbrundritt! Closing the issue.

**Comment by nipunbatra** [comment]
Or, just run with

- `python -m http.server` in the root directory and then navigating to localhost:8000 in the browser to open `index.html`.
- If you have nodejs installed, then `npm install -g http-server` and running `http-server` and localhost:8080 in the browser.
- For advanced serving one may use nginx or apache server

@rbrundritt would it be useful to add this information somewhere in the repo readme/documentation? If so, @patel-zeel or I could do a quick PR.
