### ISSUE TITLE
Rename `src/overpassScripts/*.txt` to `src/overpassScripts/*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [microsoft/satellite-imagery-labeling-tool#3]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by calebrob6** [comment]
I don't see why not. @rbrundritt do you have any issue with this?

**Comment by rbrundritt** [comment]
Just made this update. The only issue I can see is that if others try and deploy this somewhere, they may need to explicitly allow this file extension through their hosting platform.

**Comment by FloEdelmann** [comment]
Thanks for renaming!
