### ISSUE TITLE
Availability of data/pre/annotations/pre_labels.geojson

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/satellite-imagery-labeling-tool#4]
To work through the example jupyter notebook are there plans to add `data/pre/annotations/pre_labels.geojson` and the other files? Cheers

**Comment by calebrob6** [comment]
Hey @robmarkcole, I just saw these issues (and turned notifications on here). I don't think I can share the imagery for this example, but will replace the example to use some imagery of off the Planetary Computer.

**Comment by calebrob6** [comment]
Updated -- https://github.com/microsoft/satellite-imagery-labeling-tool/blob/main/example/training-example.ipynb. New file downloads some NAIP imagery and uses "building", "water", "other" labels I made with labeler.

**Comment by robmarkcole** [comment]
Fantastic, thanks!
