### ISSUE TITLE
On adding a result the project viewer does not open the project

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/satellite-imagery-labeling-tool#5]
Hi
I have created a project and can successfully view it in the project viewer. I then annotated a single task and place it in the results dir of the project, then zip it all up. However the project viewer will then not open the project, and there is no error message. The generated geojson is below - no issues loading in qgis however:

```geojson
{"type":"FeatureCollection","features":[
{"type":"Feature","properties":{"source":"Drawn|Azure Maps Satellite","class":"house","secondary_class":null,"task_name":"Robins_house_0"},"geometry":{"type":"Polygon","coordinates":[[[-0.26219,51.389004]]]}},
{"type":"Feature","properties":{"source":"Drawn|Azure Maps Satellite","class":"house","secondary_class":null,"task_name":"Robins_house_0"},"geometry":{"type":"Polygon","coordinates":[[[-0.261835,51.388774],[-0.261975,51.388854],[-0.261915,51.388891],[-0.261975,51.388929],[-0.261908,51.388962],[-0.261747,51.388875],[-0.261734,51.388883],[-0.261674,51.388849],[-0.261754,51.388799],[-0.261774,51.388808],[-0.261835,51.388774]]]}},
{"type":"Feature","properties":{"source":"Drawn|Azure Maps Satellite","class":"house","secondary_class":null,"task_name":"Robins_house_0"},"geometry":{"type":"Polygon","coordinates":[[[-0.261788,51.388766],[-0.261687,51.388829],[-0.261519,51.388728],[-0.26162,51.388661],[-0.261788,51.388766]]]}},
{"type":"Feature","properties":{"source":"Drawn|Azure Maps Satellite","class":"house","secondary_class":null,"task_name":"Robins_house_0"},"geometry":{"type":"Polygon","coordinates":[[[-0.261922,51.38836],[-0.261751,51.388439],[-0.261643,51.388358],[-0.261707,51.388326],[-0.261724,51.388341],[-0.261798,51.388314],[-0.261784,51.388299],[-0.261821,51.38828],[-0.261922,51.38836],[-0.261922,51.38836]]]}},
{"type":"Feature","properties":{"task_name":"Robins_house_0"},"geometry":{"type":"Polygon","coordinates":[[]]}}]}
```

**Comment by robmarkcole** [comment]
Potentially something to do with zipping on a mac, as if I remove the result file and zip again, this is still not opened

**Comment by robmarkcole** [comment]
the zip is at https://drive.google.com/file/d/1oYrdQsRRyCgd6XsJn4PuTFlVUi8Yz31V/view?usp=sharing

**Comment by calebrob6** [comment]
Hmmm, I can reproduce with your zip file, but not with my own (using 7zip on Windows). I labeled one grid cell and copied the result to the `results/` directory.
 
![image](https://user-images.githubusercontent.com/1088078/195761855-f58b231c-7e12-49e0-99b2-8c816dcced27.png)

**Comment by calebrob6** [comment]
Okay, I was able to get your example to work by deleting the `.DS_Store` files that Macs love to add and re-zipping.

![image](https://user-images.githubusercontent.com/1088078/195762176-e7968779-c4dc-4151-a5bc-c138a0ec3b70.png)

**Comment by robmarkcole** [comment]
Oh man those `.DS_Store` are such a PITA. Surprised it causes an issue though

**Comment by calebrob6** [comment]
Yep we'll definitely work to make this part a bit more robust!

**Comment by rbrundritt** [comment]
Looks like this is a bug in the JSZip library I'm using under the hood. I managed to figure out a workaround and have updated the project. I was able to load your file successfully with these changes.
