### ISSUE TITLE
Feature request: lasso delete

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/satellite-imagery-labeling-tool#6]
I am finding the delete tool quite tricky to use - example below I cannot delete this line. A lasso to delete would be very handy

<img width="493" alt="image" src="https://user-images.githubusercontent.com/11855322/193253663-aefa8fa1-3a18-4690-b496-d2941280a111.png">

**Comment by rbrundritt** [comment]
Thanks for the feedback. I'll keep this in mind and try and add this in the next time I have some time to work on this.

**Comment by rbrundritt** [comment]
Looks like this is a bug in the JSZip library I'm using under the hood. I managed to figure out a workaround and have updated the project. I was able to load your file successfully with these changes.

**Comment by rbrundritt** [comment]
Re-opening as mixed this up with another issue.

**Comment by rbrundritt** [comment]
I've just added two lasso/multi delete options via a "power tools" tab. Click on the lightning bolt icon on the left side and you will see these options now.
