### ISSUE TITLE
Test Service URL not catching bad URL if titiler running

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/satellite-imagery-labeling-tool#7]
I can insert a wrong URL, hit test, and there is no error. Note that titiler is running on 8000 and the image can be downloaded at `http://localhost:5005/data/m_2808060_sw_17_060_20191215.tif` so I am using URL `http://localhost:8000/cog/tiles/{z}/{x}/{y}.jpg?url=http://localhost:5005/data/m_2808060_sw_17_060_20191215.tif` and then breaking it in the test below:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/11855322/193261117-dc74f96d-eae1-45c3-ae41-8192a1bd6c4a.png">

However this functionality does appear to be working if I give a clearly wrong URL:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/11855322/193261262-de7af2c2-1fb4-4a07-94de-bf5827317ef5.png">

I dont know if this might be somehow due to using python to serve the file, I am running `python3 -m http.server 5005` and have the tif at `data/m_2808060_sw_17_060_20191215.tif`

I have also tried adding to `labeler_settings.js` but the layer is not shown - actually that appears to be a caching issue, it does appear in an incognito window

**Comment by robmarkcole** [comment]
With some more experimenting I do see the requests in the titiler logs and can get the following error using the url:
```
// 20220930130835
// http://localhost:8000/cog/tiles/15/9051/13725.jpg?url=http://localhost:5005/data/m_2808060_sw_17_060_20191215.tif

{
  "detail": "'/vsicurl/http://localhost:5005/data/m_2808060_sw_17_060_20191215.tif' does not exist in the file system, and is not recognized as a supported dataset name."
}
```

The issue appears to be the prepended `/vsicurl/`

**Comment by robmarkcole** [comment]
OK I think this is related to my using docker to run titiler, debugging. OK ruled that out by running outside docker. Now suspect that using python to serve the cog is the issue as getting error `"Range downloading not supported by this server!"` from titiler API

**Comment by calebrob6** [comment]
I'm out of time to debug right now, but FYI you can use https://titiler.xyz/ and NAIP directly on the Planetary Computer. E.g. `https://titiler.xyz/cog/tiles/{z}/{x}/{y}.jpg?url=https://naipeuwest.blob.core.windows.net/naip/v002/wa/2019/wa_60cm_2019/47122/m_4712224_sw_10_060_20191011.tif` (the bounds for this are `[-122.128736,47.622678,-122.058634,47.689833]` -- https://planetarycomputer.microsoft.com/api/stac/v1/collections/naip/items/wa_m_4712224_sw_10_060_20191011_20191218). I think the Planetary Computer is even OK with you using their titiler instance.

Will look further into this over the next few days.

**Comment by rbrundritt** [comment]
The test button simply tries to connect to the URL and see if it gets a 200 response. Basically testing for CORs access. If an error code isn't returned, the test passes.
