### ISSUE TITLE
Feature request: Selecting default map layer

### ISSUE THREAD

**Issue by calebrob6** [microsoft/satellite-imagery-labeling-tool#8]
For labeling tasks with custom layers, users will often want to start on the custom layer instead of the Azure Maps Layer. An option in the project configuration that allows to set a default layer might streamline the process a little.

**Comment by rbrundritt** [comment]
I have updated the logic that when a config is loaded, if there are any non-Azure Maps layers, it will load the first one by default. This is a fairly simple solution that allows the current configuration schema to stay the same and is a lot less work to implement across the builder and labeler tool.
